// Code generated by ent, DO NOT EDIT.

package createordersagastate

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/tkame123/ddd-sample/app/order_api/adapter/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CreateOrderSagaState {
	return predicate.CreateOrderSagaState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CreateOrderSagaState {
	return predicate.CreateOrderSagaState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CreateOrderSagaState {
	return predicate.CreateOrderSagaState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CreateOrderSagaState {
	return predicate.CreateOrderSagaState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CreateOrderSagaState {
	return predicate.CreateOrderSagaState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CreateOrderSagaState {
	return predicate.CreateOrderSagaState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CreateOrderSagaState {
	return predicate.CreateOrderSagaState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CreateOrderSagaState {
	return predicate.CreateOrderSagaState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CreateOrderSagaState {
	return predicate.CreateOrderSagaState(sql.FieldLTE(FieldID, id))
}

// CurrentEQ applies the EQ predicate on the "current" field.
func CurrentEQ(v Current) predicate.CreateOrderSagaState {
	return predicate.CreateOrderSagaState(sql.FieldEQ(FieldCurrent, v))
}

// CurrentNEQ applies the NEQ predicate on the "current" field.
func CurrentNEQ(v Current) predicate.CreateOrderSagaState {
	return predicate.CreateOrderSagaState(sql.FieldNEQ(FieldCurrent, v))
}

// CurrentIn applies the In predicate on the "current" field.
func CurrentIn(vs ...Current) predicate.CreateOrderSagaState {
	return predicate.CreateOrderSagaState(sql.FieldIn(FieldCurrent, vs...))
}

// CurrentNotIn applies the NotIn predicate on the "current" field.
func CurrentNotIn(vs ...Current) predicate.CreateOrderSagaState {
	return predicate.CreateOrderSagaState(sql.FieldNotIn(FieldCurrent, vs...))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CreateOrderSagaState) predicate.CreateOrderSagaState {
	return predicate.CreateOrderSagaState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CreateOrderSagaState) predicate.CreateOrderSagaState {
	return predicate.CreateOrderSagaState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CreateOrderSagaState) predicate.CreateOrderSagaState {
	return predicate.CreateOrderSagaState(sql.NotPredicates(p))
}
