// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tkame123/ddd-sample/app/order_api/adapter/database/ent/cancelordersagastate"
	"github.com/tkame123/ddd-sample/app/order_api/adapter/database/ent/predicate"
)

// CancelOrderSagaStateQuery is the builder for querying CancelOrderSagaState entities.
type CancelOrderSagaStateQuery struct {
	config
	ctx        *QueryContext
	order      []cancelordersagastate.OrderOption
	inters     []Interceptor
	predicates []predicate.CancelOrderSagaState
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CancelOrderSagaStateQuery builder.
func (cossq *CancelOrderSagaStateQuery) Where(ps ...predicate.CancelOrderSagaState) *CancelOrderSagaStateQuery {
	cossq.predicates = append(cossq.predicates, ps...)
	return cossq
}

// Limit the number of records to be returned by this query.
func (cossq *CancelOrderSagaStateQuery) Limit(limit int) *CancelOrderSagaStateQuery {
	cossq.ctx.Limit = &limit
	return cossq
}

// Offset to start from.
func (cossq *CancelOrderSagaStateQuery) Offset(offset int) *CancelOrderSagaStateQuery {
	cossq.ctx.Offset = &offset
	return cossq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cossq *CancelOrderSagaStateQuery) Unique(unique bool) *CancelOrderSagaStateQuery {
	cossq.ctx.Unique = &unique
	return cossq
}

// Order specifies how the records should be ordered.
func (cossq *CancelOrderSagaStateQuery) Order(o ...cancelordersagastate.OrderOption) *CancelOrderSagaStateQuery {
	cossq.order = append(cossq.order, o...)
	return cossq
}

// First returns the first CancelOrderSagaState entity from the query.
// Returns a *NotFoundError when no CancelOrderSagaState was found.
func (cossq *CancelOrderSagaStateQuery) First(ctx context.Context) (*CancelOrderSagaState, error) {
	nodes, err := cossq.Limit(1).All(setContextOp(ctx, cossq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{cancelordersagastate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cossq *CancelOrderSagaStateQuery) FirstX(ctx context.Context) *CancelOrderSagaState {
	node, err := cossq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CancelOrderSagaState ID from the query.
// Returns a *NotFoundError when no CancelOrderSagaState ID was found.
func (cossq *CancelOrderSagaStateQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cossq.Limit(1).IDs(setContextOp(ctx, cossq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{cancelordersagastate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cossq *CancelOrderSagaStateQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := cossq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CancelOrderSagaState entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CancelOrderSagaState entity is found.
// Returns a *NotFoundError when no CancelOrderSagaState entities are found.
func (cossq *CancelOrderSagaStateQuery) Only(ctx context.Context) (*CancelOrderSagaState, error) {
	nodes, err := cossq.Limit(2).All(setContextOp(ctx, cossq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{cancelordersagastate.Label}
	default:
		return nil, &NotSingularError{cancelordersagastate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cossq *CancelOrderSagaStateQuery) OnlyX(ctx context.Context) *CancelOrderSagaState {
	node, err := cossq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CancelOrderSagaState ID in the query.
// Returns a *NotSingularError when more than one CancelOrderSagaState ID is found.
// Returns a *NotFoundError when no entities are found.
func (cossq *CancelOrderSagaStateQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cossq.Limit(2).IDs(setContextOp(ctx, cossq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{cancelordersagastate.Label}
	default:
		err = &NotSingularError{cancelordersagastate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cossq *CancelOrderSagaStateQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := cossq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CancelOrderSagaStates.
func (cossq *CancelOrderSagaStateQuery) All(ctx context.Context) ([]*CancelOrderSagaState, error) {
	ctx = setContextOp(ctx, cossq.ctx, ent.OpQueryAll)
	if err := cossq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CancelOrderSagaState, *CancelOrderSagaStateQuery]()
	return withInterceptors[[]*CancelOrderSagaState](ctx, cossq, qr, cossq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cossq *CancelOrderSagaStateQuery) AllX(ctx context.Context) []*CancelOrderSagaState {
	nodes, err := cossq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CancelOrderSagaState IDs.
func (cossq *CancelOrderSagaStateQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if cossq.ctx.Unique == nil && cossq.path != nil {
		cossq.Unique(true)
	}
	ctx = setContextOp(ctx, cossq.ctx, ent.OpQueryIDs)
	if err = cossq.Select(cancelordersagastate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cossq *CancelOrderSagaStateQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := cossq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cossq *CancelOrderSagaStateQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cossq.ctx, ent.OpQueryCount)
	if err := cossq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cossq, querierCount[*CancelOrderSagaStateQuery](), cossq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cossq *CancelOrderSagaStateQuery) CountX(ctx context.Context) int {
	count, err := cossq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cossq *CancelOrderSagaStateQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cossq.ctx, ent.OpQueryExist)
	switch _, err := cossq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cossq *CancelOrderSagaStateQuery) ExistX(ctx context.Context) bool {
	exist, err := cossq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CancelOrderSagaStateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cossq *CancelOrderSagaStateQuery) Clone() *CancelOrderSagaStateQuery {
	if cossq == nil {
		return nil
	}
	return &CancelOrderSagaStateQuery{
		config:     cossq.config,
		ctx:        cossq.ctx.Clone(),
		order:      append([]cancelordersagastate.OrderOption{}, cossq.order...),
		inters:     append([]Interceptor{}, cossq.inters...),
		predicates: append([]predicate.CancelOrderSagaState{}, cossq.predicates...),
		// clone intermediate query.
		sql:  cossq.sql.Clone(),
		path: cossq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Current cancelordersagastate.Current `json:"current,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CancelOrderSagaState.Query().
//		GroupBy(cancelordersagastate.FieldCurrent).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cossq *CancelOrderSagaStateQuery) GroupBy(field string, fields ...string) *CancelOrderSagaStateGroupBy {
	cossq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CancelOrderSagaStateGroupBy{build: cossq}
	grbuild.flds = &cossq.ctx.Fields
	grbuild.label = cancelordersagastate.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Current cancelordersagastate.Current `json:"current,omitempty"`
//	}
//
//	client.CancelOrderSagaState.Query().
//		Select(cancelordersagastate.FieldCurrent).
//		Scan(ctx, &v)
func (cossq *CancelOrderSagaStateQuery) Select(fields ...string) *CancelOrderSagaStateSelect {
	cossq.ctx.Fields = append(cossq.ctx.Fields, fields...)
	sbuild := &CancelOrderSagaStateSelect{CancelOrderSagaStateQuery: cossq}
	sbuild.label = cancelordersagastate.Label
	sbuild.flds, sbuild.scan = &cossq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CancelOrderSagaStateSelect configured with the given aggregations.
func (cossq *CancelOrderSagaStateQuery) Aggregate(fns ...AggregateFunc) *CancelOrderSagaStateSelect {
	return cossq.Select().Aggregate(fns...)
}

func (cossq *CancelOrderSagaStateQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cossq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cossq); err != nil {
				return err
			}
		}
	}
	for _, f := range cossq.ctx.Fields {
		if !cancelordersagastate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cossq.path != nil {
		prev, err := cossq.path(ctx)
		if err != nil {
			return err
		}
		cossq.sql = prev
	}
	return nil
}

func (cossq *CancelOrderSagaStateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CancelOrderSagaState, error) {
	var (
		nodes = []*CancelOrderSagaState{}
		_spec = cossq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CancelOrderSagaState).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CancelOrderSagaState{config: cossq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cossq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (cossq *CancelOrderSagaStateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cossq.querySpec()
	_spec.Node.Columns = cossq.ctx.Fields
	if len(cossq.ctx.Fields) > 0 {
		_spec.Unique = cossq.ctx.Unique != nil && *cossq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cossq.driver, _spec)
}

func (cossq *CancelOrderSagaStateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(cancelordersagastate.Table, cancelordersagastate.Columns, sqlgraph.NewFieldSpec(cancelordersagastate.FieldID, field.TypeUUID))
	_spec.From = cossq.sql
	if unique := cossq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cossq.path != nil {
		_spec.Unique = true
	}
	if fields := cossq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cancelordersagastate.FieldID)
		for i := range fields {
			if fields[i] != cancelordersagastate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cossq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cossq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cossq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cossq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cossq *CancelOrderSagaStateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cossq.driver.Dialect())
	t1 := builder.Table(cancelordersagastate.Table)
	columns := cossq.ctx.Fields
	if len(columns) == 0 {
		columns = cancelordersagastate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cossq.sql != nil {
		selector = cossq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cossq.ctx.Unique != nil && *cossq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cossq.predicates {
		p(selector)
	}
	for _, p := range cossq.order {
		p(selector)
	}
	if offset := cossq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cossq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CancelOrderSagaStateGroupBy is the group-by builder for CancelOrderSagaState entities.
type CancelOrderSagaStateGroupBy struct {
	selector
	build *CancelOrderSagaStateQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cossgb *CancelOrderSagaStateGroupBy) Aggregate(fns ...AggregateFunc) *CancelOrderSagaStateGroupBy {
	cossgb.fns = append(cossgb.fns, fns...)
	return cossgb
}

// Scan applies the selector query and scans the result into the given value.
func (cossgb *CancelOrderSagaStateGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cossgb.build.ctx, ent.OpQueryGroupBy)
	if err := cossgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CancelOrderSagaStateQuery, *CancelOrderSagaStateGroupBy](ctx, cossgb.build, cossgb, cossgb.build.inters, v)
}

func (cossgb *CancelOrderSagaStateGroupBy) sqlScan(ctx context.Context, root *CancelOrderSagaStateQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cossgb.fns))
	for _, fn := range cossgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cossgb.flds)+len(cossgb.fns))
		for _, f := range *cossgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cossgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cossgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CancelOrderSagaStateSelect is the builder for selecting fields of CancelOrderSagaState entities.
type CancelOrderSagaStateSelect struct {
	*CancelOrderSagaStateQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cosss *CancelOrderSagaStateSelect) Aggregate(fns ...AggregateFunc) *CancelOrderSagaStateSelect {
	cosss.fns = append(cosss.fns, fns...)
	return cosss
}

// Scan applies the selector query and scans the result into the given value.
func (cosss *CancelOrderSagaStateSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cosss.ctx, ent.OpQuerySelect)
	if err := cosss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CancelOrderSagaStateQuery, *CancelOrderSagaStateSelect](ctx, cosss.CancelOrderSagaStateQuery, cosss, cosss.inters, v)
}

func (cosss *CancelOrderSagaStateSelect) sqlScan(ctx context.Context, root *CancelOrderSagaStateQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cosss.fns))
	for _, fn := range cosss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cosss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cosss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
