// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tkame123/ddd-sample/app/order_api/adapter/database/ent/cancelordersagastate"
	"github.com/tkame123/ddd-sample/app/order_api/adapter/database/ent/predicate"
)

// CancelOrderSagaStateDelete is the builder for deleting a CancelOrderSagaState entity.
type CancelOrderSagaStateDelete struct {
	config
	hooks    []Hook
	mutation *CancelOrderSagaStateMutation
}

// Where appends a list predicates to the CancelOrderSagaStateDelete builder.
func (cossd *CancelOrderSagaStateDelete) Where(ps ...predicate.CancelOrderSagaState) *CancelOrderSagaStateDelete {
	cossd.mutation.Where(ps...)
	return cossd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cossd *CancelOrderSagaStateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cossd.sqlExec, cossd.mutation, cossd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cossd *CancelOrderSagaStateDelete) ExecX(ctx context.Context) int {
	n, err := cossd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cossd *CancelOrderSagaStateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(cancelordersagastate.Table, sqlgraph.NewFieldSpec(cancelordersagastate.FieldID, field.TypeUUID))
	if ps := cossd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cossd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cossd.mutation.done = true
	return affected, err
}

// CancelOrderSagaStateDeleteOne is the builder for deleting a single CancelOrderSagaState entity.
type CancelOrderSagaStateDeleteOne struct {
	cossd *CancelOrderSagaStateDelete
}

// Where appends a list predicates to the CancelOrderSagaStateDelete builder.
func (cossdo *CancelOrderSagaStateDeleteOne) Where(ps ...predicate.CancelOrderSagaState) *CancelOrderSagaStateDeleteOne {
	cossdo.cossd.mutation.Where(ps...)
	return cossdo
}

// Exec executes the deletion query.
func (cossdo *CancelOrderSagaStateDeleteOne) Exec(ctx context.Context) error {
	n, err := cossdo.cossd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{cancelordersagastate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cossdo *CancelOrderSagaStateDeleteOne) ExecX(ctx context.Context) {
	if err := cossdo.Exec(ctx); err != nil {
		panic(err)
	}
}
