// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tkame123/ddd-sample/app/order_api/adapter/database/ent/createordersagastate"
	"github.com/tkame123/ddd-sample/app/order_api/adapter/database/ent/predicate"
)

// CreateOrderSagaStateUpdate is the builder for updating CreateOrderSagaState entities.
type CreateOrderSagaStateUpdate struct {
	config
	hooks    []Hook
	mutation *CreateOrderSagaStateMutation
}

// Where appends a list predicates to the CreateOrderSagaStateUpdate builder.
func (cossu *CreateOrderSagaStateUpdate) Where(ps ...predicate.CreateOrderSagaState) *CreateOrderSagaStateUpdate {
	cossu.mutation.Where(ps...)
	return cossu
}

// SetCurrent sets the "current" field.
func (cossu *CreateOrderSagaStateUpdate) SetCurrent(c createordersagastate.Current) *CreateOrderSagaStateUpdate {
	cossu.mutation.SetCurrent(c)
	return cossu
}

// SetNillableCurrent sets the "current" field if the given value is not nil.
func (cossu *CreateOrderSagaStateUpdate) SetNillableCurrent(c *createordersagastate.Current) *CreateOrderSagaStateUpdate {
	if c != nil {
		cossu.SetCurrent(*c)
	}
	return cossu
}

// SetCreatedAt sets the "created_at" field.
func (cossu *CreateOrderSagaStateUpdate) SetCreatedAt(t time.Time) *CreateOrderSagaStateUpdate {
	cossu.mutation.SetCreatedAt(t)
	return cossu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cossu *CreateOrderSagaStateUpdate) SetNillableCreatedAt(t *time.Time) *CreateOrderSagaStateUpdate {
	if t != nil {
		cossu.SetCreatedAt(*t)
	}
	return cossu
}

// SetUpdatedAt sets the "updated_at" field.
func (cossu *CreateOrderSagaStateUpdate) SetUpdatedAt(t time.Time) *CreateOrderSagaStateUpdate {
	cossu.mutation.SetUpdatedAt(t)
	return cossu
}

// Mutation returns the CreateOrderSagaStateMutation object of the builder.
func (cossu *CreateOrderSagaStateUpdate) Mutation() *CreateOrderSagaStateMutation {
	return cossu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cossu *CreateOrderSagaStateUpdate) Save(ctx context.Context) (int, error) {
	cossu.defaults()
	return withHooks(ctx, cossu.sqlSave, cossu.mutation, cossu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cossu *CreateOrderSagaStateUpdate) SaveX(ctx context.Context) int {
	affected, err := cossu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cossu *CreateOrderSagaStateUpdate) Exec(ctx context.Context) error {
	_, err := cossu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cossu *CreateOrderSagaStateUpdate) ExecX(ctx context.Context) {
	if err := cossu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cossu *CreateOrderSagaStateUpdate) defaults() {
	if _, ok := cossu.mutation.UpdatedAt(); !ok {
		v := createordersagastate.UpdateDefaultUpdatedAt()
		cossu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cossu *CreateOrderSagaStateUpdate) check() error {
	if v, ok := cossu.mutation.Current(); ok {
		if err := createordersagastate.CurrentValidator(v); err != nil {
			return &ValidationError{Name: "current", err: fmt.Errorf(`ent: validator failed for field "CreateOrderSagaState.current": %w`, err)}
		}
	}
	return nil
}

func (cossu *CreateOrderSagaStateUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cossu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(createordersagastate.Table, createordersagastate.Columns, sqlgraph.NewFieldSpec(createordersagastate.FieldID, field.TypeUUID))
	if ps := cossu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cossu.mutation.Current(); ok {
		_spec.SetField(createordersagastate.FieldCurrent, field.TypeEnum, value)
	}
	if value, ok := cossu.mutation.CreatedAt(); ok {
		_spec.SetField(createordersagastate.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := cossu.mutation.UpdatedAt(); ok {
		_spec.SetField(createordersagastate.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cossu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{createordersagastate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cossu.mutation.done = true
	return n, nil
}

// CreateOrderSagaStateUpdateOne is the builder for updating a single CreateOrderSagaState entity.
type CreateOrderSagaStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CreateOrderSagaStateMutation
}

// SetCurrent sets the "current" field.
func (cossuo *CreateOrderSagaStateUpdateOne) SetCurrent(c createordersagastate.Current) *CreateOrderSagaStateUpdateOne {
	cossuo.mutation.SetCurrent(c)
	return cossuo
}

// SetNillableCurrent sets the "current" field if the given value is not nil.
func (cossuo *CreateOrderSagaStateUpdateOne) SetNillableCurrent(c *createordersagastate.Current) *CreateOrderSagaStateUpdateOne {
	if c != nil {
		cossuo.SetCurrent(*c)
	}
	return cossuo
}

// SetCreatedAt sets the "created_at" field.
func (cossuo *CreateOrderSagaStateUpdateOne) SetCreatedAt(t time.Time) *CreateOrderSagaStateUpdateOne {
	cossuo.mutation.SetCreatedAt(t)
	return cossuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cossuo *CreateOrderSagaStateUpdateOne) SetNillableCreatedAt(t *time.Time) *CreateOrderSagaStateUpdateOne {
	if t != nil {
		cossuo.SetCreatedAt(*t)
	}
	return cossuo
}

// SetUpdatedAt sets the "updated_at" field.
func (cossuo *CreateOrderSagaStateUpdateOne) SetUpdatedAt(t time.Time) *CreateOrderSagaStateUpdateOne {
	cossuo.mutation.SetUpdatedAt(t)
	return cossuo
}

// Mutation returns the CreateOrderSagaStateMutation object of the builder.
func (cossuo *CreateOrderSagaStateUpdateOne) Mutation() *CreateOrderSagaStateMutation {
	return cossuo.mutation
}

// Where appends a list predicates to the CreateOrderSagaStateUpdate builder.
func (cossuo *CreateOrderSagaStateUpdateOne) Where(ps ...predicate.CreateOrderSagaState) *CreateOrderSagaStateUpdateOne {
	cossuo.mutation.Where(ps...)
	return cossuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cossuo *CreateOrderSagaStateUpdateOne) Select(field string, fields ...string) *CreateOrderSagaStateUpdateOne {
	cossuo.fields = append([]string{field}, fields...)
	return cossuo
}

// Save executes the query and returns the updated CreateOrderSagaState entity.
func (cossuo *CreateOrderSagaStateUpdateOne) Save(ctx context.Context) (*CreateOrderSagaState, error) {
	cossuo.defaults()
	return withHooks(ctx, cossuo.sqlSave, cossuo.mutation, cossuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cossuo *CreateOrderSagaStateUpdateOne) SaveX(ctx context.Context) *CreateOrderSagaState {
	node, err := cossuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cossuo *CreateOrderSagaStateUpdateOne) Exec(ctx context.Context) error {
	_, err := cossuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cossuo *CreateOrderSagaStateUpdateOne) ExecX(ctx context.Context) {
	if err := cossuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cossuo *CreateOrderSagaStateUpdateOne) defaults() {
	if _, ok := cossuo.mutation.UpdatedAt(); !ok {
		v := createordersagastate.UpdateDefaultUpdatedAt()
		cossuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cossuo *CreateOrderSagaStateUpdateOne) check() error {
	if v, ok := cossuo.mutation.Current(); ok {
		if err := createordersagastate.CurrentValidator(v); err != nil {
			return &ValidationError{Name: "current", err: fmt.Errorf(`ent: validator failed for field "CreateOrderSagaState.current": %w`, err)}
		}
	}
	return nil
}

func (cossuo *CreateOrderSagaStateUpdateOne) sqlSave(ctx context.Context) (_node *CreateOrderSagaState, err error) {
	if err := cossuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(createordersagastate.Table, createordersagastate.Columns, sqlgraph.NewFieldSpec(createordersagastate.FieldID, field.TypeUUID))
	id, ok := cossuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CreateOrderSagaState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cossuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, createordersagastate.FieldID)
		for _, f := range fields {
			if !createordersagastate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != createordersagastate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cossuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cossuo.mutation.Current(); ok {
		_spec.SetField(createordersagastate.FieldCurrent, field.TypeEnum, value)
	}
	if value, ok := cossuo.mutation.CreatedAt(); ok {
		_spec.SetField(createordersagastate.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := cossuo.mutation.UpdatedAt(); ok {
		_spec.SetField(createordersagastate.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &CreateOrderSagaState{config: cossuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cossuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{createordersagastate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cossuo.mutation.done = true
	return _node, nil
}
