// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tkame123/ddd-sample/app/order_api/adapter/database/ent/createordersagastate"
)

// CreateOrderSagaStateCreate is the builder for creating a CreateOrderSagaState entity.
type CreateOrderSagaStateCreate struct {
	config
	mutation *CreateOrderSagaStateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCurrent sets the "current" field.
func (cossc *CreateOrderSagaStateCreate) SetCurrent(c createordersagastate.Current) *CreateOrderSagaStateCreate {
	cossc.mutation.SetCurrent(c)
	return cossc
}

// SetCreatedAt sets the "created_at" field.
func (cossc *CreateOrderSagaStateCreate) SetCreatedAt(t time.Time) *CreateOrderSagaStateCreate {
	cossc.mutation.SetCreatedAt(t)
	return cossc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cossc *CreateOrderSagaStateCreate) SetNillableCreatedAt(t *time.Time) *CreateOrderSagaStateCreate {
	if t != nil {
		cossc.SetCreatedAt(*t)
	}
	return cossc
}

// SetUpdatedAt sets the "updated_at" field.
func (cossc *CreateOrderSagaStateCreate) SetUpdatedAt(t time.Time) *CreateOrderSagaStateCreate {
	cossc.mutation.SetUpdatedAt(t)
	return cossc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cossc *CreateOrderSagaStateCreate) SetNillableUpdatedAt(t *time.Time) *CreateOrderSagaStateCreate {
	if t != nil {
		cossc.SetUpdatedAt(*t)
	}
	return cossc
}

// SetID sets the "id" field.
func (cossc *CreateOrderSagaStateCreate) SetID(u uuid.UUID) *CreateOrderSagaStateCreate {
	cossc.mutation.SetID(u)
	return cossc
}

// Mutation returns the CreateOrderSagaStateMutation object of the builder.
func (cossc *CreateOrderSagaStateCreate) Mutation() *CreateOrderSagaStateMutation {
	return cossc.mutation
}

// Save creates the CreateOrderSagaState in the database.
func (cossc *CreateOrderSagaStateCreate) Save(ctx context.Context) (*CreateOrderSagaState, error) {
	cossc.defaults()
	return withHooks(ctx, cossc.sqlSave, cossc.mutation, cossc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cossc *CreateOrderSagaStateCreate) SaveX(ctx context.Context) *CreateOrderSagaState {
	v, err := cossc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cossc *CreateOrderSagaStateCreate) Exec(ctx context.Context) error {
	_, err := cossc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cossc *CreateOrderSagaStateCreate) ExecX(ctx context.Context) {
	if err := cossc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cossc *CreateOrderSagaStateCreate) defaults() {
	if _, ok := cossc.mutation.CreatedAt(); !ok {
		v := createordersagastate.DefaultCreatedAt()
		cossc.mutation.SetCreatedAt(v)
	}
	if _, ok := cossc.mutation.UpdatedAt(); !ok {
		v := createordersagastate.DefaultUpdatedAt()
		cossc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cossc *CreateOrderSagaStateCreate) check() error {
	if _, ok := cossc.mutation.Current(); !ok {
		return &ValidationError{Name: "current", err: errors.New(`ent: missing required field "CreateOrderSagaState.current"`)}
	}
	if v, ok := cossc.mutation.Current(); ok {
		if err := createordersagastate.CurrentValidator(v); err != nil {
			return &ValidationError{Name: "current", err: fmt.Errorf(`ent: validator failed for field "CreateOrderSagaState.current": %w`, err)}
		}
	}
	if _, ok := cossc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CreateOrderSagaState.created_at"`)}
	}
	if _, ok := cossc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CreateOrderSagaState.updated_at"`)}
	}
	return nil
}

func (cossc *CreateOrderSagaStateCreate) sqlSave(ctx context.Context) (*CreateOrderSagaState, error) {
	if err := cossc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cossc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cossc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	cossc.mutation.id = &_node.ID
	cossc.mutation.done = true
	return _node, nil
}

func (cossc *CreateOrderSagaStateCreate) createSpec() (*CreateOrderSagaState, *sqlgraph.CreateSpec) {
	var (
		_node = &CreateOrderSagaState{config: cossc.config}
		_spec = sqlgraph.NewCreateSpec(createordersagastate.Table, sqlgraph.NewFieldSpec(createordersagastate.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = cossc.conflict
	if id, ok := cossc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := cossc.mutation.Current(); ok {
		_spec.SetField(createordersagastate.FieldCurrent, field.TypeEnum, value)
		_node.Current = value
	}
	if value, ok := cossc.mutation.CreatedAt(); ok {
		_spec.SetField(createordersagastate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := cossc.mutation.UpdatedAt(); ok {
		_spec.SetField(createordersagastate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CreateOrderSagaState.Create().
//		SetCurrent(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreateOrderSagaStateUpsert) {
//			SetCurrent(v+v).
//		}).
//		Exec(ctx)
func (cossc *CreateOrderSagaStateCreate) OnConflict(opts ...sql.ConflictOption) *CreateOrderSagaStateUpsertOne {
	cossc.conflict = opts
	return &CreateOrderSagaStateUpsertOne{
		create: cossc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CreateOrderSagaState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (cossc *CreateOrderSagaStateCreate) OnConflictColumns(columns ...string) *CreateOrderSagaStateUpsertOne {
	cossc.conflict = append(cossc.conflict, sql.ConflictColumns(columns...))
	return &CreateOrderSagaStateUpsertOne{
		create: cossc,
	}
}

type (
	// CreateOrderSagaStateUpsertOne is the builder for "upsert"-ing
	//  one CreateOrderSagaState node.
	CreateOrderSagaStateUpsertOne struct {
		create *CreateOrderSagaStateCreate
	}

	// CreateOrderSagaStateUpsert is the "OnConflict" setter.
	CreateOrderSagaStateUpsert struct {
		*sql.UpdateSet
	}
)

// SetCurrent sets the "current" field.
func (u *CreateOrderSagaStateUpsert) SetCurrent(v createordersagastate.Current) *CreateOrderSagaStateUpsert {
	u.Set(createordersagastate.FieldCurrent, v)
	return u
}

// UpdateCurrent sets the "current" field to the value that was provided on create.
func (u *CreateOrderSagaStateUpsert) UpdateCurrent() *CreateOrderSagaStateUpsert {
	u.SetExcluded(createordersagastate.FieldCurrent)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CreateOrderSagaStateUpsert) SetCreatedAt(v time.Time) *CreateOrderSagaStateUpsert {
	u.Set(createordersagastate.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CreateOrderSagaStateUpsert) UpdateCreatedAt() *CreateOrderSagaStateUpsert {
	u.SetExcluded(createordersagastate.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CreateOrderSagaStateUpsert) SetUpdatedAt(v time.Time) *CreateOrderSagaStateUpsert {
	u.Set(createordersagastate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CreateOrderSagaStateUpsert) UpdateUpdatedAt() *CreateOrderSagaStateUpsert {
	u.SetExcluded(createordersagastate.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CreateOrderSagaState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(createordersagastate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CreateOrderSagaStateUpsertOne) UpdateNewValues() *CreateOrderSagaStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(createordersagastate.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CreateOrderSagaState.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CreateOrderSagaStateUpsertOne) Ignore() *CreateOrderSagaStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreateOrderSagaStateUpsertOne) DoNothing() *CreateOrderSagaStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreateOrderSagaStateCreate.OnConflict
// documentation for more info.
func (u *CreateOrderSagaStateUpsertOne) Update(set func(*CreateOrderSagaStateUpsert)) *CreateOrderSagaStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreateOrderSagaStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetCurrent sets the "current" field.
func (u *CreateOrderSagaStateUpsertOne) SetCurrent(v createordersagastate.Current) *CreateOrderSagaStateUpsertOne {
	return u.Update(func(s *CreateOrderSagaStateUpsert) {
		s.SetCurrent(v)
	})
}

// UpdateCurrent sets the "current" field to the value that was provided on create.
func (u *CreateOrderSagaStateUpsertOne) UpdateCurrent() *CreateOrderSagaStateUpsertOne {
	return u.Update(func(s *CreateOrderSagaStateUpsert) {
		s.UpdateCurrent()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CreateOrderSagaStateUpsertOne) SetCreatedAt(v time.Time) *CreateOrderSagaStateUpsertOne {
	return u.Update(func(s *CreateOrderSagaStateUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CreateOrderSagaStateUpsertOne) UpdateCreatedAt() *CreateOrderSagaStateUpsertOne {
	return u.Update(func(s *CreateOrderSagaStateUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CreateOrderSagaStateUpsertOne) SetUpdatedAt(v time.Time) *CreateOrderSagaStateUpsertOne {
	return u.Update(func(s *CreateOrderSagaStateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CreateOrderSagaStateUpsertOne) UpdateUpdatedAt() *CreateOrderSagaStateUpsertOne {
	return u.Update(func(s *CreateOrderSagaStateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CreateOrderSagaStateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CreateOrderSagaStateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreateOrderSagaStateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CreateOrderSagaStateUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CreateOrderSagaStateUpsertOne.ID is not supported by MySQL driver. Use CreateOrderSagaStateUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CreateOrderSagaStateUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CreateOrderSagaStateCreateBulk is the builder for creating many CreateOrderSagaState entities in bulk.
type CreateOrderSagaStateCreateBulk struct {
	config
	err      error
	builders []*CreateOrderSagaStateCreate
	conflict []sql.ConflictOption
}

// Save creates the CreateOrderSagaState entities in the database.
func (cosscb *CreateOrderSagaStateCreateBulk) Save(ctx context.Context) ([]*CreateOrderSagaState, error) {
	if cosscb.err != nil {
		return nil, cosscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(cosscb.builders))
	nodes := make([]*CreateOrderSagaState, len(cosscb.builders))
	mutators := make([]Mutator, len(cosscb.builders))
	for i := range cosscb.builders {
		func(i int, root context.Context) {
			builder := cosscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CreateOrderSagaStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cosscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = cosscb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cosscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cosscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cosscb *CreateOrderSagaStateCreateBulk) SaveX(ctx context.Context) []*CreateOrderSagaState {
	v, err := cosscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cosscb *CreateOrderSagaStateCreateBulk) Exec(ctx context.Context) error {
	_, err := cosscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cosscb *CreateOrderSagaStateCreateBulk) ExecX(ctx context.Context) {
	if err := cosscb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CreateOrderSagaState.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CreateOrderSagaStateUpsert) {
//			SetCurrent(v+v).
//		}).
//		Exec(ctx)
func (cosscb *CreateOrderSagaStateCreateBulk) OnConflict(opts ...sql.ConflictOption) *CreateOrderSagaStateUpsertBulk {
	cosscb.conflict = opts
	return &CreateOrderSagaStateUpsertBulk{
		create: cosscb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CreateOrderSagaState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (cosscb *CreateOrderSagaStateCreateBulk) OnConflictColumns(columns ...string) *CreateOrderSagaStateUpsertBulk {
	cosscb.conflict = append(cosscb.conflict, sql.ConflictColumns(columns...))
	return &CreateOrderSagaStateUpsertBulk{
		create: cosscb,
	}
}

// CreateOrderSagaStateUpsertBulk is the builder for "upsert"-ing
// a bulk of CreateOrderSagaState nodes.
type CreateOrderSagaStateUpsertBulk struct {
	create *CreateOrderSagaStateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CreateOrderSagaState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(createordersagastate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CreateOrderSagaStateUpsertBulk) UpdateNewValues() *CreateOrderSagaStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(createordersagastate.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CreateOrderSagaState.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CreateOrderSagaStateUpsertBulk) Ignore() *CreateOrderSagaStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CreateOrderSagaStateUpsertBulk) DoNothing() *CreateOrderSagaStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CreateOrderSagaStateCreateBulk.OnConflict
// documentation for more info.
func (u *CreateOrderSagaStateUpsertBulk) Update(set func(*CreateOrderSagaStateUpsert)) *CreateOrderSagaStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CreateOrderSagaStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetCurrent sets the "current" field.
func (u *CreateOrderSagaStateUpsertBulk) SetCurrent(v createordersagastate.Current) *CreateOrderSagaStateUpsertBulk {
	return u.Update(func(s *CreateOrderSagaStateUpsert) {
		s.SetCurrent(v)
	})
}

// UpdateCurrent sets the "current" field to the value that was provided on create.
func (u *CreateOrderSagaStateUpsertBulk) UpdateCurrent() *CreateOrderSagaStateUpsertBulk {
	return u.Update(func(s *CreateOrderSagaStateUpsert) {
		s.UpdateCurrent()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CreateOrderSagaStateUpsertBulk) SetCreatedAt(v time.Time) *CreateOrderSagaStateUpsertBulk {
	return u.Update(func(s *CreateOrderSagaStateUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CreateOrderSagaStateUpsertBulk) UpdateCreatedAt() *CreateOrderSagaStateUpsertBulk {
	return u.Update(func(s *CreateOrderSagaStateUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CreateOrderSagaStateUpsertBulk) SetUpdatedAt(v time.Time) *CreateOrderSagaStateUpsertBulk {
	return u.Update(func(s *CreateOrderSagaStateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CreateOrderSagaStateUpsertBulk) UpdateUpdatedAt() *CreateOrderSagaStateUpsertBulk {
	return u.Update(func(s *CreateOrderSagaStateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CreateOrderSagaStateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CreateOrderSagaStateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CreateOrderSagaStateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CreateOrderSagaStateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
