// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/tkame123/ddd-sample/app/kitchen_api/adapter/database"
	"github.com/tkame123/ddd-sample/app/kitchen_api/adapter/message"
	"github.com/tkame123/ddd-sample/app/kitchen_api/adapter/message/sns"
	"github.com/tkame123/ddd-sample/app/kitchen_api/di/provider"
	"github.com/tkame123/ddd-sample/app/kitchen_api/usecase/create_ticket"
)

// Injectors from wire.go:

func InitializeCommandConsumer() (*message.CommandConsumer, func(), error) {
	consumerConfig := provider.NewConsumerConfig()
	envConfig, err := provider.NewENV()
	if err != nil {
		return nil, nil, err
	}
	config, err := provider.NewAWSConfig()
	if err != nil {
		return nil, nil, err
	}
	client, err := provider.NewSQSClient(config)
	if err != nil {
		return nil, nil, err
	}
	repository := database.NewRepository()
	snsClient, err := provider.NewSNSClient(config)
	if err != nil {
		return nil, nil, err
	}
	publisher := sns.NewPublisher(envConfig, snsClient)
	domain_eventPublisher := message.NewEventPublisher(publisher)
	createTicket := create_ticket.NewService(repository, domain_eventPublisher)
	commandConsumer := message.NewCommandConsumer(consumerConfig, envConfig, client, createTicket)
	return commandConsumer, func() {
	}, nil
}

// wire.go:

var providerCommandConsumerSet = wire.NewSet(message.NewCommandConsumer, create_ticket.NewService, message.NewEventPublisher, database.NewRepository, sns.NewPublisher, provider.NewENV, provider.NewAWSConfig, provider.NewConsumerConfig, provider.NewSQSClient, provider.NewSNSClient)
