// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/tkame123/ddd-sample/app/order_api/adapter/database"
	"github.com/tkame123/ddd-sample/app/order_api/adapter/gateway/api"
	"github.com/tkame123/ddd-sample/app/order_api/adapter/message"
	"github.com/tkame123/ddd-sample/app/order_api/adapter/proxy"
	"github.com/tkame123/ddd-sample/app/order_api/di/provider"
	"github.com/tkame123/ddd-sample/app/order_api/usecase/create_order"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func InitializeAPIServer() (connect.Server, func(), error) {
	envConfig, err := provider.NewENV()
	if err != nil {
		return connect.Server{}, nil, err
	}
	client, cleanup, err := provider.NewOrderApiDB(envConfig)
	if err != nil {
		return connect.Server{}, nil, err
	}
	repository := database.NewRepository(client)
	config, err := provider.NewAWSConfig()
	if err != nil {
		cleanup()
		return connect.Server{}, nil, err
	}
	snsClient, err := provider.NewSNSClient(config)
	if err != nil {
		cleanup()
		return connect.Server{}, nil, err
	}
	publisher := message.NewEventPublisher(envConfig, snsClient)
	server := connect.NewServer(repository, publisher)
	return server, func() {
		cleanup()
	}, nil
}

func InitializeEventConsumer() (*message.EventConsumer, func(), error) {
	consumerConfig := provider.NewConsumerConfig()
	envConfig, err := provider.NewENV()
	if err != nil {
		return nil, nil, err
	}
	config, err := provider.NewAWSConfig()
	if err != nil {
		return nil, nil, err
	}
	client, err := provider.NewSQSClient(config)
	if err != nil {
		return nil, nil, err
	}
	entClient, cleanup, err := provider.NewOrderApiDB(envConfig)
	if err != nil {
		return nil, nil, err
	}
	repository := database.NewRepository(entClient)
	snsClient, err := provider.NewSNSClient(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	publisher := message.NewEventPublisher(envConfig, snsClient)
	createOrder := create_order.NewService(repository, publisher)
	kitchenAPI := proxy.NewKitchenAPI(repository, publisher)
	billingAPI := proxy.NewBillingAPI()
	eventConsumer := message.NewEventConsumer(consumerConfig, envConfig, client, repository, createOrder, kitchenAPI, billingAPI)
	return eventConsumer, func() {
		cleanup()
	}, nil
}

// wire.go:

var providerServerSet = wire.NewSet(connect.NewServer, database.NewRepository, message.NewEventPublisher, provider.NewENV, provider.NewAWSConfig, provider.NewOrderApiDB, provider.NewSNSClient)

var providerEventConsumerSet = wire.NewSet(message.NewEventConsumer, message.NewEventPublisher, database.NewRepository, create_order.NewService, proxy.NewBillingAPI, proxy.NewKitchenAPI, provider.NewENV, provider.NewAWSConfig, provider.NewConsumerConfig, provider.NewOrderApiDB, provider.NewSQSClient, provider.NewSNSClient)
