// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/tkame123/ddd-sample/app/order_api/adapter/database"
	"github.com/tkame123/ddd-sample/app/order_api/adapter/gateway/api"
	"github.com/tkame123/ddd-sample/app/order_api/di/provider"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func InitializeOrderAPIServer() (connect.Server, func(), error) {
	envConfig, err := provider.NewENV()
	if err != nil {
		return connect.Server{}, nil, err
	}
	client, cleanup, err := provider.NewOrderApiDB(envConfig)
	if err != nil {
		return connect.Server{}, nil, err
	}
	repository := database.NewRepository(client)
	server := connect.NewServer(repository)
	return server, func() {
		cleanup()
	}, nil
}

// wire.go:

var providerOrderAPIServerSet = wire.NewSet(connect.NewServer, database.NewRepository, provider.NewENV, provider.NewOrderApiDB)
