// Code generated by ent, DO NOT EDIT.

package cancelordersagastate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/tkame123/ddd-sample/app/order_api/adapter/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldLTE(FieldID, id))
}

// TicketID applies equality check predicate on the "ticket_id" field. It's identical to TicketIDEQ.
func TicketID(v uuid.UUID) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldEQ(FieldTicketID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldEQ(FieldUpdatedAt, v))
}

// CurrentEQ applies the EQ predicate on the "current" field.
func CurrentEQ(v Current) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldEQ(FieldCurrent, v))
}

// CurrentNEQ applies the NEQ predicate on the "current" field.
func CurrentNEQ(v Current) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldNEQ(FieldCurrent, v))
}

// CurrentIn applies the In predicate on the "current" field.
func CurrentIn(vs ...Current) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldIn(FieldCurrent, vs...))
}

// CurrentNotIn applies the NotIn predicate on the "current" field.
func CurrentNotIn(vs ...Current) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldNotIn(FieldCurrent, vs...))
}

// TicketIDEQ applies the EQ predicate on the "ticket_id" field.
func TicketIDEQ(v uuid.UUID) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldEQ(FieldTicketID, v))
}

// TicketIDNEQ applies the NEQ predicate on the "ticket_id" field.
func TicketIDNEQ(v uuid.UUID) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldNEQ(FieldTicketID, v))
}

// TicketIDIn applies the In predicate on the "ticket_id" field.
func TicketIDIn(vs ...uuid.UUID) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldIn(FieldTicketID, vs...))
}

// TicketIDNotIn applies the NotIn predicate on the "ticket_id" field.
func TicketIDNotIn(vs ...uuid.UUID) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldNotIn(FieldTicketID, vs...))
}

// TicketIDGT applies the GT predicate on the "ticket_id" field.
func TicketIDGT(v uuid.UUID) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldGT(FieldTicketID, v))
}

// TicketIDGTE applies the GTE predicate on the "ticket_id" field.
func TicketIDGTE(v uuid.UUID) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldGTE(FieldTicketID, v))
}

// TicketIDLT applies the LT predicate on the "ticket_id" field.
func TicketIDLT(v uuid.UUID) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldLT(FieldTicketID, v))
}

// TicketIDLTE applies the LTE predicate on the "ticket_id" field.
func TicketIDLTE(v uuid.UUID) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldLTE(FieldTicketID, v))
}

// TicketIDIsNil applies the IsNil predicate on the "ticket_id" field.
func TicketIDIsNil() predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldIsNull(FieldTicketID))
}

// TicketIDNotNil applies the NotNil predicate on the "ticket_id" field.
func TicketIDNotNil() predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldNotNull(FieldTicketID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CancelOrderSagaState) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CancelOrderSagaState) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CancelOrderSagaState) predicate.CancelOrderSagaState {
	return predicate.CancelOrderSagaState(sql.NotPredicates(p))
}
